<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\alarms\alarms.csproj" />
    <ProjectReference Include="..\communication\communication.csproj" />
    <ProjectReference Include="..\compiler\compiler.csproj" />
    <ProjectReference Include="..\components\components.csproj" />
    <ProjectReference Include="..\console\console.csproj" />
    <ProjectReference Include="..\discovery\discovery.csproj" />
    <ProjectReference Include="..\events\events.csproj" />
    <ProjectReference Include="..\historian\historian.csproj" />
    <ProjectReference Include="..\machinelearning\machinelearning.csproj" />
    <ProjectReference Include="..\project\project.csproj" />
    <ProjectReference Include="..\scheduler\scheduler.csproj" />
    <ProjectReference Include="..\screeneditor\screeneditor.csproj" />
    <ProjectReference Include="..\scripter\scripter.csproj" />
    <ProjectReference Include="..\simulator\simulator.csproj" />
    <ProjectReference Include="..\tagengine\tagengine.csproj" />
    <ProjectReference Include="..\tools\tools.csproj" />
    <ProjectReference Include="..\workspace\workspace.csproj" />
  </ItemGroup>

</Project>