<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AccuTrack.SDK</RootNamespace>
    <AssemblyName>AccuTrack.SDK</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="NModbus.Serial" Version="3.0.81" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="1.5.374.118" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

</Project>
