<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Communication.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RuntimeModules\Communication\Communication.csproj" />
    <ProjectReference Include="..\..\RuntimeModules\ExecutionEngine\ExecutionEngine.csproj" />
  </ItemGroup>

</Project>
